/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adminstrator;
import Scheduler.Hall_Management;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Main.*;
/**
 *
 * @author Ahmed
 */
public class Admin extends javax.swing.JFrame {

    private String B_ID;
    /**
     *
     * Creates new form Admin
     */
    public Admin(String B_ID) {
        initComponents();
        this.B_ID=B_ID;
    }
    public void set_B_ID(String B_ID){
        this.B_ID=B_ID;
    }
    public String get_B_ID(){
        return B_ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        View_User_button = new javax.swing.JButton();
        Search_Filter_User_Button = new javax.swing.JButton();
        Delete_user_Button = new javax.swing.JButton();
        View_Bookings = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Delete_Account = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Delete_User_Table = new javax.swing.JTable();
        Delete_Uesr_Field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Delete_User_Search = new javax.swing.JButton();
        Delete_User_Button = new javax.swing.JButton();
        Delete_User_Clear = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        Delete_User_Button1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        Display_Bookings = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Booking_S_Table = new javax.swing.JTable();
        Booking_S_Label = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Delete_Cust_Account = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Delete_Customer_Table = new javax.swing.JTable();
        Delete_Customer_Field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Delete_Customer_Search = new javax.swing.JButton();
        Delete_Customer_Button = new javax.swing.JButton();
        Delete_Customer_Clear = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        View_Customer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cus_Table = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        View_Booking = new javax.swing.JPanel();
        UpcomingBooking_B = new javax.swing.JButton();
        PastBooking_B = new javax.swing.JButton();
        AllBooking_B = new javax.swing.JButton();
        CancelledBooking_B = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Search_user = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        User_search = new javax.swing.JTable();
        Search_U_Button = new javax.swing.JButton();
        Search_U_Field = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        Search_Button1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        View_User_Info = new javax.swing.JPanel();
        View_Scheduler = new javax.swing.JButton();
        View_Admin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        User_Info = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        View_Cus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Customer_Search = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Customer_Search_T = new javax.swing.JTable();
        Customer_S_Button = new javax.swing.JButton();
        Search_Customer_F = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Admin_Menu.setBackground(new java.awt.Color(255, 255, 255));
        Admin_Menu.setPreferredSize(new java.awt.Dimension(1000, 600));
        Admin_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hall Symphony Inc.");
        Admin_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 230, 70));

        jButton3.setBackground(new java.awt.Color(51, 0, 51));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Admin_Menu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 150, 50));

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        View_User_button.setBackground(new java.awt.Color(51, 0, 51));
        View_User_button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        View_User_button.setForeground(new java.awt.Color(255, 255, 255));
        View_User_button.setText("View User Info");
        View_User_button.setBorder(null);
        View_User_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_User_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(View_User_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, 50));

        Search_Filter_User_Button.setBackground(new java.awt.Color(51, 0, 51));
        Search_Filter_User_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Search_Filter_User_Button.setForeground(new java.awt.Color(255, 255, 255));
        Search_Filter_User_Button.setText("Search & Filter User Info");
        Search_Filter_User_Button.setBorder(null);
        Search_Filter_User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Filter_User_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(Search_Filter_User_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 50));

        Delete_user_Button.setBackground(new java.awt.Color(51, 0, 51));
        Delete_user_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_user_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_user_Button.setText("Delete User Account");
        Delete_user_Button.setBorder(null);
        Delete_user_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_user_ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(Delete_user_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 240, 50));

        View_Bookings.setBackground(new java.awt.Color(51, 0, 51));
        View_Bookings.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        View_Bookings.setForeground(new java.awt.Color(255, 255, 255));
        View_Bookings.setText("View & Filter Bookings");
        View_Bookings.setBorder(null);
        View_Bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_BookingsActionPerformed(evt);
            }
        });
        jPanel4.add(View_Bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 50));

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log out");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 50));

        Admin_Menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 300, 600));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adminstrator Menu");
        Admin_Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 510, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Admin_Menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, 10));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Admin_Menu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        getContentPane().add(Admin_Menu, "card2");

        Delete_Account.setBackground(new java.awt.Color(255, 255, 255));
        Delete_Account.setPreferredSize(new java.awt.Dimension(1000, 600));
        Delete_Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete_User_Table.setBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Delete_User_Table.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Email", "Role", "Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Delete_User_Table.setGridColor(new java.awt.Color(51, 0, 51));
        Delete_User_Table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Table.getTableHeader().setResizingAllowed(false);
        Delete_User_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(Delete_User_Table);

        Delete_Account.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 271, 781, 126));

        Delete_Uesr_Field.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Uesr_Field.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_Uesr_Field.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Uesr_Field.setBorder(null);
        Delete_Uesr_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Uesr_FieldActionPerformed(evt);
            }
        });
        Delete_Account.add(Delete_Uesr_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 163, 243, 47));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter User ID To Delete");
        Delete_Account.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 323, -1));

        Delete_User_Search.setBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_User_Search.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Search.setText("Search");
        Delete_User_Search.setBorder(null);
        Delete_User_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_SearchActionPerformed(evt);
            }
        });
        Delete_Account.add(Delete_User_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 193, 120, 40));

        Delete_User_Button.setBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_User_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Button.setText("Delete");
        Delete_User_Button.setBorder(null);
        Delete_User_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_ButtonActionPerformed(evt);
            }
        });
        Delete_Account.add(Delete_User_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 453, 158, 49));

        Delete_User_Clear.setBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Clear.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_User_Clear.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Clear.setText("Clear");
        Delete_User_Clear.setBorder(null);
        Delete_User_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_ClearActionPerformed(evt);
            }
        });
        Delete_Account.add(Delete_User_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 453, 135, 49));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Delete User Account");
        Delete_Account.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 31, 378, 45));

        jButton19.setBackground(new java.awt.Color(51, 0, 51));
        jButton19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Back");
        jButton19.setBorder(null);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Delete_Account.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 36, 145, 40));

        Delete_User_Button1.setBackground(new java.awt.Color(51, 0, 51));
        Delete_User_Button1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_User_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_Button1.setText("Click Here To Delete Customer Info ");
        Delete_User_Button1.setBorder(null);
        Delete_User_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_Button1ActionPerformed(evt);
            }
        });
        Delete_Account.add(Delete_User_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 545, 1000, 49));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Delete_Account.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        getContentPane().add(Delete_Account, "card7");

        Display_Bookings.setBackground(new java.awt.Color(255, 255, 255));
        Display_Bookings.setForeground(new java.awt.Color(255, 255, 255));
        Display_Bookings.setPreferredSize(new java.awt.Dimension(1000, 600));
        Display_Bookings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Booking_S_Table.setBackground(new java.awt.Color(51, 0, 51));
        Booking_S_Table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Booking_S_Table.setForeground(new java.awt.Color(255, 255, 255));
        Booking_S_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Booking ID", "HallID", "Hall Type", "Start Date", "End date", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Booking_S_Table.setGridColor(new java.awt.Color(51, 0, 51));
        Booking_S_Table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        Booking_S_Table.getTableHeader().setResizingAllowed(false);
        Booking_S_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(Booking_S_Table);

        Display_Bookings.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 990, 410));

        Booking_S_Label.setBackground(new java.awt.Color(51, 0, 51));
        Booking_S_Label.setForeground(new java.awt.Color(255, 255, 255));
        Display_Bookings.add(Booking_S_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 6, 303, 58));

        jButton9.setBackground(new java.awt.Color(51, 0, 51));
        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Back");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Display_Bookings.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 14, 150, 60));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Display_Bookings.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(Display_Bookings, "card13");

        Delete_Cust_Account.setBackground(new java.awt.Color(255, 255, 255));
        Delete_Cust_Account.setPreferredSize(new java.awt.Dimension(1000, 600));
        Delete_Cust_Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delete_Customer_Table.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Customer_Table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Delete_Customer_Table.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Customer_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "First Name", "Last Name", "Email", "Role", "Password", "Address", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Delete_Customer_Table.getTableHeader().setResizingAllowed(false);
        Delete_Customer_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(Delete_Customer_Table);

        Delete_Cust_Account.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 939, 132));

        Delete_Customer_Field.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Customer_Field.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_Customer_Field.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Customer_Field.setBorder(null);
        Delete_Customer_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Customer_FieldActionPerformed(evt);
            }
        });
        Delete_Cust_Account.add(Delete_Customer_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 163, 243, 47));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Customer ID To Delete");
        Delete_Cust_Account.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, 416, -1));

        Delete_Customer_Search.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Customer_Search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_Customer_Search.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Customer_Search.setText("Search");
        Delete_Customer_Search.setBorder(null);
        Delete_Customer_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Customer_SearchActionPerformed(evt);
            }
        });
        Delete_Cust_Account.add(Delete_Customer_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 171, 120, 50));

        Delete_Customer_Button.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Customer_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_Customer_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Customer_Button.setText("Delete");
        Delete_Customer_Button.setBorder(null);
        Delete_Customer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Customer_ButtonActionPerformed(evt);
            }
        });
        Delete_Cust_Account.add(Delete_Customer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 488, 158, 49));

        Delete_Customer_Clear.setBackground(new java.awt.Color(51, 0, 51));
        Delete_Customer_Clear.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Delete_Customer_Clear.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Customer_Clear.setText("Clear");
        Delete_Customer_Clear.setBorder(null);
        Delete_Customer_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Customer_ClearActionPerformed(evt);
            }
        });
        Delete_Cust_Account.add(Delete_Customer_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 488, 135, 49));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Delete Customer Account");
        Delete_Cust_Account.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 25, 430, 45));

        jButton20.setBackground(new java.awt.Color(51, 0, 51));
        jButton20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Back");
        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Delete_Cust_Account.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 145, 49));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Delete_Cust_Account.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(Delete_Cust_Account, "card7");

        View_Customer.setBackground(new java.awt.Color(255, 255, 255));
        View_Customer.setPreferredSize(new java.awt.Dimension(1000, 600));
        View_Customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(51, 0, 51));

        Cus_Table.setBackground(new java.awt.Color(51, 0, 51));
        Cus_Table.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Cus_Table.setForeground(new java.awt.Color(255, 255, 255));
        Cus_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Email", "Role", "Password", "Address", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Cus_Table.setGridColor(new java.awt.Color(51, 0, 51));
        Cus_Table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        Cus_Table.getTableHeader().setResizingAllowed(false);
        Cus_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Cus_Table);

        View_Customer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 988, 430));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("View Currrent Customers");
        View_Customer.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButton15.setBackground(new java.awt.Color(51, 0, 51));
        jButton15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Back");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        View_Customer.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 160, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        View_Customer.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(View_Customer, "card10");

        View_Booking.setBackground(new java.awt.Color(255, 255, 255));
        View_Booking.setPreferredSize(new java.awt.Dimension(1000, 600));

        UpcomingBooking_B.setBackground(new java.awt.Color(242, 242, 242));
        UpcomingBooking_B.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        UpcomingBooking_B.setText("Upcoming Bookings");
        UpcomingBooking_B.setBorder(null);
        UpcomingBooking_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcomingBooking_BActionPerformed(evt);
            }
        });

        PastBooking_B.setBackground(new java.awt.Color(242, 242, 242));
        PastBooking_B.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        PastBooking_B.setText("Past Bookings ");
        PastBooking_B.setBorder(null);
        PastBooking_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastBooking_BActionPerformed(evt);
            }
        });

        AllBooking_B.setBackground(new java.awt.Color(51, 0, 51));
        AllBooking_B.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AllBooking_B.setForeground(new java.awt.Color(255, 255, 255));
        AllBooking_B.setText("All Booking ");
        AllBooking_B.setBorder(null);
        AllBooking_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllBooking_BActionPerformed(evt);
            }
        });

        CancelledBooking_B.setBackground(new java.awt.Color(51, 0, 51));
        CancelledBooking_B.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CancelledBooking_B.setForeground(new java.awt.Color(255, 255, 255));
        CancelledBooking_B.setText("Cancelled Booking ");
        CancelledBooking_B.setBorder(null);
        CancelledBooking_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelledBooking_BActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout View_BookingLayout = new javax.swing.GroupLayout(View_Booking);
        View_Booking.setLayout(View_BookingLayout);
        View_BookingLayout.setHorizontalGroup(
            View_BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_BookingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AllBooking_B, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PastBooking_B, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelledBooking_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpcomingBooking_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        View_BookingLayout.setVerticalGroup(
            View_BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllBooking_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(View_BookingLayout.createSequentialGroup()
                .addGroup(View_BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpcomingBooking_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PastBooking_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelledBooking_B, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(View_Booking, "card9");

        Search_user.setBackground(new java.awt.Color(255, 255, 255));
        Search_user.setPreferredSize(new java.awt.Dimension(1000, 600));
        Search_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        User_search.setBackground(new java.awt.Color(51, 0, 51));
        User_search.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        User_search.setForeground(new java.awt.Color(255, 255, 255));
        User_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", null},
                {null, null, null, "", null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Uesr ID", "User Name", "User Email", "Hall Role", "User Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        User_search.setGridColor(new java.awt.Color(51, 0, 51));
        User_search.setSelectionBackground(new java.awt.Color(51, 0, 51));
        User_search.getTableHeader().setResizingAllowed(false);
        User_search.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(User_search);

        Search_user.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, 755, 383));

        Search_U_Button.setBackground(new java.awt.Color(51, 0, 51));
        Search_U_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Search_U_Button.setForeground(new java.awt.Color(255, 255, 255));
        Search_U_Button.setText("Search");
        Search_U_Button.setBorder(null);
        Search_U_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_U_ButtonActionPerformed(evt);
            }
        });
        Search_user.add(Search_U_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 125, 130, 40));

        Search_U_Field.setBackground(new java.awt.Color(51, 0, 51));
        Search_U_Field.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Search_U_Field.setForeground(new java.awt.Color(255, 255, 255));
        Search_U_Field.setText("Type here to search");
        Search_U_Field.setBorder(null);
        Search_U_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Search_U_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Search_U_FieldFocusLost(evt);
            }
        });
        Search_U_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_U_FieldActionPerformed(evt);
            }
        });
        Search_user.add(Search_U_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 117, 376, 50));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Search & Filter for Customer's Info");
        Search_user.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 416, 55));

        jButton16.setBackground(new java.awt.Color(51, 0, 51));
        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Back");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Search_user.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 163, 47));

        Search_Button1.setBackground(new java.awt.Color(51, 0, 51));
        Search_Button1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Search_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Search_Button1.setText("Search & Filter Customer");
        Search_Button1.setBorder(null);
        Search_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Button1ActionPerformed(evt);
            }
        });
        Search_user.add(Search_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 562, 750, 40));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Search_user.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 610));

        getContentPane().add(Search_user, "card5");

        View_User_Info.setBackground(new java.awt.Color(255, 255, 255));
        View_User_Info.setPreferredSize(new java.awt.Dimension(1000, 600));
        View_User_Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        View_Scheduler.setBackground(new java.awt.Color(51, 0, 51));
        View_Scheduler.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        View_Scheduler.setForeground(new java.awt.Color(255, 255, 255));
        View_Scheduler.setText("Display Current Schedulars");
        View_Scheduler.setBorder(null);
        View_Scheduler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_SchedulerActionPerformed(evt);
            }
        });
        View_User_Info.add(View_Scheduler, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 503, -1, 52));

        View_Admin.setBackground(new java.awt.Color(51, 0, 51));
        View_Admin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        View_Admin.setForeground(new java.awt.Color(255, 255, 255));
        View_Admin.setText("Display Current Admins");
        View_Admin.setToolTipText("");
        View_Admin.setActionCommand("Click here to display Current Admins");
        View_Admin.setBorder(null);
        View_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_AdminActionPerformed(evt);
            }
        });
        View_User_Info.add(View_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 503, -1, 52));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        User_Info.setBackground(new java.awt.Color(51, 0, 51));
        User_Info.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        User_Info.setForeground(new java.awt.Color(255, 255, 255));
        User_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", null},
                {null, null, null, "", null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "User Name", "User Email", "User Role", "User Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        User_Info.setGridColor(new java.awt.Color(51, 0, 51));
        User_Info.setSelectionBackground(new java.awt.Color(51, 0, 51));
        User_Info.getTableHeader().setResizingAllowed(false);
        User_Info.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(User_Info);

        View_User_Info.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 116, 965, 352));

        jButton7.setBackground(new java.awt.Color(51, 0, 51));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        View_User_Info.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 27, 194, 52));

        View_Cus.setBackground(new java.awt.Color(51, 0, 51));
        View_Cus.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        View_Cus.setForeground(new java.awt.Color(255, 255, 255));
        View_Cus.setText("Display Current Customers");
        View_Cus.setBorder(null);
        View_Cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_CusActionPerformed(evt);
            }
        });
        View_User_Info.add(View_Cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 503, -1, 52));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("View Currrent Users");
        View_User_Info.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 25, -1, 52));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        View_User_Info.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        getContentPane().add(View_User_Info, "card4");

        Customer_Search.setBackground(new java.awt.Color(255, 255, 255));
        Customer_Search.setPreferredSize(new java.awt.Dimension(1000, 600));
        Customer_Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Customer_Search_T.setBackground(new java.awt.Color(51, 0, 51));
        Customer_Search_T.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Customer_Search_T.setForeground(new java.awt.Color(255, 255, 255));
        Customer_Search_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", null, null, null, null, null},
                {null, null, null, "", null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Email", "Role", "Password", "Address", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Customer_Search_T.setGridColor(new java.awt.Color(51, 0, 51));
        Customer_Search_T.setSelectionBackground(new java.awt.Color(51, 0, 51));
        Customer_Search_T.getTableHeader().setResizingAllowed(false);
        Customer_Search_T.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Customer_Search_T);

        Customer_Search.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 940, 383));

        Customer_S_Button.setBackground(new java.awt.Color(51, 0, 51));
        Customer_S_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Customer_S_Button.setForeground(new java.awt.Color(255, 255, 255));
        Customer_S_Button.setText("Search");
        Customer_S_Button.setBorder(null);
        Customer_S_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_S_ButtonActionPerformed(evt);
            }
        });
        Customer_Search.add(Customer_S_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 124, 115, 40));

        Search_Customer_F.setBackground(new java.awt.Color(51, 0, 51));
        Search_Customer_F.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Search_Customer_F.setForeground(new java.awt.Color(255, 255, 255));
        Search_Customer_F.setText("Type here to search");
        Search_Customer_F.setBorder(null);
        Search_Customer_F.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Search_Customer_FFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Search_Customer_FFocusLost(evt);
            }
        });
        Search_Customer_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Customer_FActionPerformed(evt);
            }
        });
        Customer_Search.add(Search_Customer_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 376, 46));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Search & Filter for User's Info");
        Customer_Search.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 22, 416, 64));

        jButton17.setBackground(new java.awt.Color(51, 0, 51));
        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Back");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Customer_Search.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 33, 147, 50));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        Customer_Search.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        getContentPane().add(Customer_Search, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_User_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_User_buttonActionPerformed
        Admin_Menu.setVisible(false);
        View_User_Info.setVisible(true);
        //        DefaultTableModel model=(DefaultTableModel) jHall_Info.getModel();
        //        model.setRowCount(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_View_User_buttonActionPerformed

    private void Search_Filter_User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Filter_User_ButtonActionPerformed
        Admin_Menu.setVisible(false);
        Search_user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Filter_User_ButtonActionPerformed

    private void Delete_user_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_user_ButtonActionPerformed
        Admin_Menu.setVisible(false);
        Delete_Account.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_user_ButtonActionPerformed

    private void View_BookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_BookingsActionPerformed
        Admin_Menu.setVisible(false);
        View_Booking.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_View_BookingsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Display_Bookings.setVisible(false);
        View_Booking.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Delete_Customer_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Customer_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Customer_FieldActionPerformed

    private void Delete_Customer_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Customer_SearchActionPerformed
        Admin_Management admin= new Admin_Management(null,null,null,null,null);
        String Delete =Delete_Customer_Field.getText();
        DefaultTableModel model=(DefaultTableModel) Delete_Customer_Table.getModel();
        model.setRowCount(0);
        admin.Select_Specific_User("src\\database\\Customer.txt", model, Delete);
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Customer_SearchActionPerformed

    private void Delete_Customer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Customer_ButtonActionPerformed
        Customer_Management customer=new Customer_Management(null,null,null,null,null);
        String delete_C_ID=Delete_Customer_Field.getText();

        if (delete_C_ID.isEmpty() || delete_C_ID.equals("Enter Customer ID")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Hall ID.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        customer.delete_info("src\\database\\Customer.txt",delete_C_ID);
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Customer_ButtonActionPerformed

    private void Delete_Customer_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Customer_ClearActionPerformed
        Delete_Customer_Field.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Customer_ClearActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Delete_Cust_Account.setVisible(false);
        Delete_Account.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        View_Customer.setVisible(false);
        View_User_Info.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void UpcomingBooking_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcomingBooking_BActionPerformed
        View_Booking.setVisible(false);
        Display_Bookings.setVisible(true);
        DefaultTableModel model=(DefaultTableModel) Booking_S_Table.getModel();
        model.setRowCount(0);

        Booking_Management book=new Booking_Management(null,null,null,0,0,null,null,null,null,null,null,null);
        Booking_S_Label.setText("Upcoming Bookings");
        Booking_S_Label.setFont(new Font("Segoe Print",Font.BOLD,24));
        book.viewBookings(model, "Upcoming");
        // TODO add your handling code here:
    }//GEN-LAST:event_UpcomingBooking_BActionPerformed

    private void PastBooking_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastBooking_BActionPerformed
        View_Booking.setVisible(false);
        Display_Bookings.setVisible(true);
        DefaultTableModel model=(DefaultTableModel) Booking_S_Table.getModel();
        model.setRowCount(0);

        Booking_Management book=new Booking_Management(null,null,null,0,0,null,null,null,null,null,null,null);
        Booking_S_Label.setText("Past Bookings");
        Booking_S_Label.setFont(new Font("Segoe Print",Font.BOLD,24));
        book.viewBookings(model, "Past");

        // TODO add your handling code here:
    }//GEN-LAST:event_PastBooking_BActionPerformed

    private void AllBooking_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllBooking_BActionPerformed
        View_Booking.setVisible(false);
        Display_Bookings.setVisible(true);
        DefaultTableModel model=(DefaultTableModel) Booking_S_Table.getModel();
        model.setRowCount(0);
        Hall_Management view=new Hall_Management(null,null,null,0,0);
        Booking_S_Label.setText("All Bookings");
        Booking_S_Label.setFont(new Font("Segoe Print",Font.BOLD,24));
        view.view_file("src\\database\\Booking.txt", model);
        // TODO add your handling code here:
    }//GEN-LAST:event_AllBooking_BActionPerformed

    private void CancelledBooking_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelledBooking_BActionPerformed
        View_Booking.setVisible(false);
        Display_Bookings.setVisible(true);
        DefaultTableModel model=(DefaultTableModel) Booking_S_Table.getModel();
        model.setRowCount(0);

        Booking_Management book=new Booking_Management(null,null,null,0,0,null,null,null,null,null,null,null);
        Booking_S_Label.setText("Cancelled Bookings");
        Booking_S_Label.setFont(new Font("Segoe Print",Font.BOLD,24));
        book.viewBookings(model, "Cancelled");
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelledBooking_BActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        View_Booking.setVisible(false);
        Admin_Menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Delete_Uesr_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Uesr_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Uesr_FieldActionPerformed

    private void Delete_User_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_SearchActionPerformed
        Admin_Management admin= new Admin_Management(null,null,null,null,null);
        String delete =Delete_Uesr_Field.getText();
        DefaultTableModel model=(DefaultTableModel) Delete_User_Table.getModel();
        model.setRowCount(0);
        admin.Select_Specific_User("src\\database\\database.txt", model, delete);
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_User_SearchActionPerformed

    private void Delete_User_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_ButtonActionPerformed
        Admin_Management adm=new Admin_Management(null,null,null,null,null);
        String delete_U_ID=Delete_Uesr_Field.getText();

        if (delete_U_ID.isEmpty() || delete_U_ID.equals("Enter User ID")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Hall ID.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        adm.delete_info("src\\database\\database.txt",delete_U_ID);

        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_User_ButtonActionPerformed

    private void Delete_User_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_ClearActionPerformed
        Delete_Uesr_Field.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_User_ClearActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Delete_Account.setVisible(false);
        Admin_Menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void Delete_User_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_Button1ActionPerformed
        Delete_Account.setVisible(false);
        Delete_Cust_Account.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_User_Button1ActionPerformed

    private void Search_U_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_U_ButtonActionPerformed
        Admin_Management ad= new Admin_Management(null,null,null,null,null);
        String search=Search_U_Field.getText();
        DefaultTableModel model=(DefaultTableModel) User_search.getModel();
        model.setRowCount(0);
        ad.filter_info(model, search);
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_U_ButtonActionPerformed

    private void Search_U_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_U_FieldFocusGained
        if(Search_U_Field.getText().equals("Type here to search")){
            Search_U_Field.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_U_FieldFocusGained

    private void Search_U_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_U_FieldFocusLost
        if(Search_U_Field.getText().isEmpty()){
            Search_U_Field.setText("Type here to search");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_U_FieldFocusLost

    private void Search_U_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_U_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_U_FieldActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Search_user.setVisible(false);
        Admin_Menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void Search_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Button1ActionPerformed
        Search_user.setVisible(false);
        Customer_Search.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Button1ActionPerformed

    private void View_SchedulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_SchedulerActionPerformed
        DefaultTableModel model=(DefaultTableModel) User_Info.getModel();
        model.setRowCount(0);
        Admin_Management Admin=new Admin_Management(null,null,null,null,null);
        Admin.view_User_Info("src\\database\\Database.txt", model, "Schedular");
        // TODO add your handling code here:
    }//GEN-LAST:event_View_SchedulerActionPerformed

    private void View_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_AdminActionPerformed
        DefaultTableModel model=(DefaultTableModel) User_Info.getModel();
        model.setRowCount(0);
        Admin_Management Admin=new Admin_Management(null,null,null,null,null);
        Admin.view_User_Info("src\\database\\Database.txt", model, "Adminstrator");
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_View_AdminActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        View_User_Info.setVisible(false);
        Admin_Menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void View_CusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_CusActionPerformed
        View_User_Info.setVisible(false);
        View_Customer.setVisible(true);
        DefaultTableModel model=(DefaultTableModel) Cus_Table.getModel();
        model.setRowCount(0);
        Customer_Management Cust=new Customer_Management(null,null,null,null,null);
        Cust.view_User_Info("src\\database\\Customer.txt", model, "Customer");

        // TODO add your handling code here:
    }//GEN-LAST:event_View_CusActionPerformed

    private void Customer_S_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_S_ButtonActionPerformed
        Customer_Management Cust= new Customer_Management(null,null,null,null,null);
        String search=Search_Customer_F.getText();
        DefaultTableModel model=(DefaultTableModel) Customer_Search_T.getModel();
        model.setRowCount(0);
        Cust.filter_info(model, search);
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_S_ButtonActionPerformed

    private void Search_Customer_FFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_Customer_FFocusGained
        if(Search_Customer_F.getText().equals("Type here to search")){
            Search_Customer_F.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Customer_FFocusGained

    private void Search_Customer_FFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_Customer_FFocusLost
        if(Search_Customer_F.getText().isEmpty()){
            Search_Customer_F.setText("Type here to search");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Customer_FFocusLost

    private void Search_Customer_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Customer_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_Customer_FActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Admin(null).setVisible(false);
        this.dispose();
        new Main().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        Customer_Search.setVisible(false);
        Search_user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Admin_Menu;
    private javax.swing.JButton AllBooking_B;
    private javax.swing.JLabel Booking_S_Label;
    private javax.swing.JTable Booking_S_Table;
    private javax.swing.JButton CancelledBooking_B;
    private javax.swing.JTable Cus_Table;
    private javax.swing.JButton Customer_S_Button;
    private javax.swing.JPanel Customer_Search;
    private javax.swing.JTable Customer_Search_T;
    private javax.swing.JPanel Delete_Account;
    private javax.swing.JPanel Delete_Cust_Account;
    protected javax.swing.JButton Delete_Customer_Button;
    protected javax.swing.JButton Delete_Customer_Clear;
    protected javax.swing.JTextField Delete_Customer_Field;
    protected javax.swing.JButton Delete_Customer_Search;
    protected javax.swing.JTable Delete_Customer_Table;
    protected javax.swing.JTextField Delete_Uesr_Field;
    protected javax.swing.JButton Delete_User_Button;
    protected javax.swing.JButton Delete_User_Button1;
    protected javax.swing.JButton Delete_User_Clear;
    protected javax.swing.JButton Delete_User_Search;
    protected javax.swing.JTable Delete_User_Table;
    private javax.swing.JButton Delete_user_Button;
    private javax.swing.JPanel Display_Bookings;
    private javax.swing.JButton PastBooking_B;
    private javax.swing.JButton Search_Button1;
    private javax.swing.JTextField Search_Customer_F;
    private javax.swing.JButton Search_Filter_User_Button;
    private javax.swing.JButton Search_U_Button;
    private javax.swing.JTextField Search_U_Field;
    private javax.swing.JPanel Search_user;
    private javax.swing.JButton UpcomingBooking_B;
    private javax.swing.JTable User_Info;
    private javax.swing.JTable User_search;
    private javax.swing.JButton View_Admin;
    private javax.swing.JPanel View_Booking;
    private javax.swing.JButton View_Bookings;
    private javax.swing.JButton View_Cus;
    private javax.swing.JPanel View_Customer;
    private javax.swing.JButton View_Scheduler;
    private javax.swing.JPanel View_User_Info;
    private javax.swing.JButton View_User_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    protected javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    protected javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    protected javax.swing.JLabel jLabel24;
    protected javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    protected javax.swing.JScrollPane jScrollPane6;
    protected javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
