/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Scheduler.Hall_Menu_GUI;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import Adminstrator.*;
import Customer.*;
import Staff_Acc_Manager.*;

/**
 *
 * @author sagfoopro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        EXITButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SignUpButtonLogIn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        IDLogin = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        EmailLogin = new javax.swing.JTextField();
        LogInButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        PasswordLogin = new javax.swing.JPasswordField();
        StaffLogInPanelButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        GetPhoneNumber = new javax.swing.JTextField();
        CreateAccointLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        WelcomeBackLabel = new javax.swing.JLabel();
        LoginButtonSignUp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        GetAddress = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        GetPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        GetLastName = new javax.swing.JTextField();
        SignUpButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        GetEmail = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        GetFirstName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        StaffLoginPanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        SignUpButtonLogIn1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        Staff_Email = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        StaffIDLogin = new javax.swing.JTextField();
        EXITButtonStaff = new javax.swing.JButton();
        StaffLogInButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        StaffPasswordLogin = new javax.swing.JPasswordField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMainPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EXITButton.setBackground(new java.awt.Color(51, 0, 51));
        EXITButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EXITButton.setForeground(new java.awt.Color(255, 255, 255));
        EXITButton.setText("EXIT");
        EXITButton.setBorder(null);
        EXITButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(EXITButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hall Symphony Inc.");
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 390, 70));

        jPanel10.setBackground(new java.awt.Color(51, 0, 51));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New here?");

        SignUpButtonLogIn.setBackground(new java.awt.Color(51, 0, 51));
        SignUpButtonLogIn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SignUpButtonLogIn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButtonLogIn.setText("Sign Up");
        SignUpButtonLogIn.setBorder(null);
        SignUpButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(SignUpButtonLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUpButtonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        LoginPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 0, 300, 656));

        jPanel11.setBackground(new java.awt.Color(102, 0, 102));

        IDLogin.setBackground(new java.awt.Color(51, 0, 51));
        IDLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        IDLogin.setForeground(new java.awt.Color(255, 255, 255));
        IDLogin.setText("ID");
        IDLogin.setBorder(null);
        IDLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDLoginFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IDLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        LoginPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 290, 302, -1));

        jPanel14.setBackground(new java.awt.Color(102, 0, 102));

        EmailLogin.setBackground(new java.awt.Color(51, 0, 51));
        EmailLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EmailLogin.setForeground(new java.awt.Color(255, 255, 255));
        EmailLogin.setText("Email");
        EmailLogin.setBorder(null);
        EmailLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailLoginFocusLost(evt);
            }
        });
        EmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addComponent(EmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        LoginPanel.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 218, -1, -1));

        LogInButton.setBackground(new java.awt.Color(51, 0, 51));
        LogInButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("Log In");
        LogInButton.setBorder(null);
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(LogInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 434, 123, 54));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Log In");
        LoginPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 137, 247, 63));

        jPanel15.setBackground(new java.awt.Color(102, 0, 102));

        PasswordLogin.setBackground(new java.awt.Color(51, 0, 51));
        PasswordLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PasswordLogin.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLogin.setText("Password");
        PasswordLogin.setBorder(null);
        PasswordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PasswordLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        LoginPanel.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 362, 302, -1));

        StaffLogInPanelButton.setBackground(new java.awt.Color(51, 0, 51));
        StaffLogInPanelButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        StaffLogInPanelButton.setForeground(new java.awt.Color(255, 255, 255));
        StaffLogInPanelButton.setText("Staff Login");
        StaffLogInPanelButton.setBorder(null);
        StaffLogInPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffLogInPanelButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(StaffLogInPanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 288, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        LoginPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        MainMainPanel.add(LoginPanel, "card7");

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 0, 102));

        GetPhoneNumber.setBackground(new java.awt.Color(51, 0, 51));
        GetPhoneNumber.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GetPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        GetPhoneNumber.setText("Phone Number");
        GetPhoneNumber.setBorder(null);
        GetPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetPhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetPhoneNumberFocusLost(evt);
            }
        });
        GetPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPhoneNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(GetPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        RegisterPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        CreateAccointLabel.setBackground(new java.awt.Color(255, 255, 255));
        CreateAccointLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CreateAccointLabel.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccointLabel.setText("Create Account");
        RegisterPanel.add(CreateAccointLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, 62));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        WelcomeBackLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        WelcomeBackLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeBackLabel.setText("Welcome Back!");

        LoginButtonSignUp.setBackground(new java.awt.Color(51, 0, 51));
        LoginButtonSignUp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LoginButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        LoginButtonSignUp.setText("Log In");
        LoginButtonSignUp.setBorder(null);
        LoginButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(WelcomeBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LoginButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(WelcomeBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(LoginButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        RegisterPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        GetAddress.setBackground(new java.awt.Color(51, 0, 51));
        GetAddress.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GetAddress.setForeground(new java.awt.Color(255, 255, 255));
        GetAddress.setText("Address");
        GetAddress.setBorder(null);
        GetAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetAddressFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(GetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        RegisterPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        GetPassword.setBackground(new java.awt.Color(51, 0, 51));
        GetPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        GetPassword.setForeground(new java.awt.Color(255, 255, 255));
        GetPassword.setText("Password");
        GetPassword.setBorder(null);
        GetPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(GetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        RegisterPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        GetLastName.setBackground(new java.awt.Color(51, 0, 51));
        GetLastName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GetLastName.setForeground(new java.awt.Color(255, 255, 255));
        GetLastName.setText("Last Name");
        GetLastName.setBorder(null);
        GetLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetLastNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GetLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        RegisterPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 289, -1));

        SignUpButton.setBackground(new java.awt.Color(51, 0, 51));
        SignUpButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("SIGN UP");
        SignUpButton.setBorder(null);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        RegisterPanel.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 153, 48));

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        GetEmail.setBackground(new java.awt.Color(51, 0, 51));
        GetEmail.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GetEmail.setForeground(new java.awt.Color(255, 255, 255));
        GetEmail.setText("Email");
        GetEmail.setBorder(null);
        GetEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(GetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        RegisterPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jPanel13.setBackground(new java.awt.Color(102, 0, 102));

        GetFirstName.setBackground(new java.awt.Color(51, 0, 51));
        GetFirstName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        GetFirstName.setForeground(new java.awt.Color(255, 255, 255));
        GetFirstName.setText("First Name");
        GetFirstName.setBorder(null);
        GetFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GetFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetFirstNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(GetFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GetFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        RegisterPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        RegisterPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        MainMainPanel.add(RegisterPanel, "card3");

        StaffLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        StaffLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(51, 0, 51));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("You Are not a Staff?");

        SignUpButtonLogIn1.setBackground(new java.awt.Color(51, 0, 51));
        SignUpButtonLogIn1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SignUpButtonLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButtonLogIn1.setText("Back");
        SignUpButtonLogIn1.setBorder(null);
        SignUpButtonLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonLogIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(SignUpButtonLogIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(SignUpButtonLogIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        StaffLoginPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 0, 310, 656));

        jPanel17.setBackground(new java.awt.Color(102, 0, 102));

        Staff_Email.setBackground(new java.awt.Color(51, 0, 51));
        Staff_Email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Staff_Email.setForeground(new java.awt.Color(255, 255, 255));
        Staff_Email.setText("Email");
        Staff_Email.setBorder(null);
        Staff_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Staff_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Staff_EmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(Staff_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Staff_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        StaffLoginPanel.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 54));

        jPanel16.setBackground(new java.awt.Color(102, 0, 102));

        StaffIDLogin.setBackground(new java.awt.Color(51, 0, 51));
        StaffIDLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        StaffIDLogin.setForeground(new java.awt.Color(255, 255, 255));
        StaffIDLogin.setText("Staff ID");
        StaffIDLogin.setBorder(null);
        StaffIDLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StaffIDLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                StaffIDLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(StaffIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffIDLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        StaffLoginPanel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        EXITButtonStaff.setBackground(new java.awt.Color(51, 0, 51));
        EXITButtonStaff.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EXITButtonStaff.setForeground(new java.awt.Color(255, 255, 255));
        EXITButtonStaff.setText("EXIT");
        EXITButtonStaff.setBorder(null);
        EXITButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITButtonStaffActionPerformed(evt);
            }
        });
        StaffLoginPanel.add(EXITButtonStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        StaffLogInButton.setBackground(new java.awt.Color(51, 0, 51));
        StaffLogInButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        StaffLogInButton.setForeground(new java.awt.Color(255, 255, 255));
        StaffLogInButton.setText("Log In");
        StaffLogInButton.setBorder(null);
        StaffLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffLogInButtonActionPerformed(evt);
            }
        });
        StaffLoginPanel.add(StaffLogInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 123, 54));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Staff Log In");
        StaffLoginPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 83, 247, 63));

        jPanel18.setBackground(new java.awt.Color(102, 0, 102));

        StaffPasswordLogin.setBackground(new java.awt.Color(51, 0, 51));
        StaffPasswordLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        StaffPasswordLogin.setForeground(new java.awt.Color(255, 255, 255));
        StaffPasswordLogin.setText("Password");
        StaffPasswordLogin.setBorder(null);
        StaffPasswordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StaffPasswordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                StaffPasswordLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(StaffPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffPasswordLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        StaffLoginPanel.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pexels-photo-6985132.jpg"))); // NOI18N
        StaffLoginPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        MainMainPanel.add(StaffLoginPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonLogInActionPerformed
        RegisterPanel.setVisible(true);
        LoginPanel.setVisible(false);
    }//GEN-LAST:event_SignUpButtonLogInActionPerformed

    private void IDLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDLoginFocusGained
        if (IDLogin.getText().equals("ID")) {
            IDLogin.setText("");
        }
    }//GEN-LAST:event_IDLoginFocusGained

    private void EmailLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailLoginFocusGained
        if (EmailLogin.getText().equals("Email")) {
            EmailLogin.setText("");
        }
    }//GEN-LAST:event_EmailLoginFocusGained

    private void EmailLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailLoginFocusLost
        if (EmailLogin.getText().isEmpty()) {
            EmailLogin.setText("Email");
        }
    }//GEN-LAST:event_EmailLoginFocusLost

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        String email = EmailLogin.getText().trim();
        String id = IDLogin.getText().trim();
        cus cusGUI = new cus(null,null);
        cusGUI.setCuID(id);
        String password = PasswordLogin.getText().trim();
        cusGUI.setCuPass(password);
        Customer_Login customerLogin = new Customer_Login();
        boolean isLoginSuccessful = customerLogin.cus_log(email, id, password);

        if (isLoginSuccessful) {
            // Retrieve customer information
            Customer customer = cusGUI.getCustomerInfo(id, email, password);
            
            if (customer != null) {
                // Assuming getCustomerInfo populates these fields
                String currentCustomerId = customer.getCustomerID();
                cusGUI.ShowCustomerID.setText(currentCustomerId);
                cusGUI.ShowCustomerFirstName.setText(customer.getFirstName());
                cusGUI.ShowCustomerLastName.setText(customer.getLastName());
                cusGUI.ShowCustomerEmail.setText(customer.getEmail());
                cusGUI.ShowCustomerMobileNumber.setText(customer.getPhoneNumber());
                cusGUI.ShowCustomerAddress.setText(customer.getAddress());

                // Create Customer object with updated information

                cusGUI.displayCustomerProfile(customer); // Show customer profile
                new Main().setVisible(false);
                this.dispose();
                cusGUI.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error retrieving customer information", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 

        // Clear the input fields

    }//GEN-LAST:event_LogInButtonActionPerformed

    private void PasswordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordLoginFocusGained
        if (PasswordLogin.getText().equals("Password")) {
            PasswordLogin.setText("");
        }
    }//GEN-LAST:event_PasswordLoginFocusGained

    private void PasswordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordLoginFocusLost
        if (PasswordLogin.getText().isEmpty()) {
            PasswordLogin.setText("Password");
        }
    }//GEN-LAST:event_PasswordLoginFocusLost

    private void GetPhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetPhoneNumberFocusGained
        if (GetPhoneNumber.getText().equals("Phone Number")) {
            GetPhoneNumber.setText("");
        }
    }//GEN-LAST:event_GetPhoneNumberFocusGained

    private void GetPhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetPhoneNumberFocusLost
        if (GetPhoneNumber.getText().isEmpty()) {
            GetPhoneNumber.setText("Phone Number");
        }
    }//GEN-LAST:event_GetPhoneNumberFocusLost

    private void LoginButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonSignUpActionPerformed
        LoginPanel.setVisible(true);
        RegisterPanel.setVisible(false);
    }//GEN-LAST:event_LoginButtonSignUpActionPerformed

    private void GetAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetAddressFocusGained
        if (GetAddress.getText().equals("Address")) {
            GetAddress.setText("");
        }
    }//GEN-LAST:event_GetAddressFocusGained

    private void GetAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetAddressFocusLost
        if (GetAddress.getText().isEmpty()) {
            GetAddress.setText("Address");
        }
    }//GEN-LAST:event_GetAddressFocusLost

    private void GetPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetPasswordFocusGained
        if (GetPassword.getText().equals("Password")) {
            GetPassword.setText("");
        }
    }//GEN-LAST:event_GetPasswordFocusGained

    private void GetPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetPasswordFocusLost
        if (GetPassword.getText().isEmpty()) {
            GetPassword.setText("Password");
        }
    }//GEN-LAST:event_GetPasswordFocusLost

    private void GetLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetLastNameFocusGained
        if (GetLastName.getText().equals("Last Name")) {
            GetLastName.setText("");
        }
    }//GEN-LAST:event_GetLastNameFocusGained

    private void GetLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetLastNameFocusLost
        if (GetLastName.getText().isEmpty()) {
            GetLastName.setText("Last Name");
        }
    }//GEN-LAST:event_GetLastNameFocusLost

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        Customer customerRegister = new Customer(null,null,null,null,null,null,null);

        String firstName = GetFirstName.getText().trim();
        String lastName = GetLastName.getText().trim();
        String email = GetEmail.getText().trim();
        String password = GetPassword.getText().trim();
        String address = GetAddress.getText().trim();
        String phoneNumber = GetPhoneNumber.getText().trim();

        String customerId = customerRegister.registerCustomer(firstName, lastName, email, password, address, phoneNumber);

        if (customerId != null) {
            // Clear the fields
            GetFirstName.setText("");
            GetLastName.setText("");
            GetEmail.setText("");
            GetPassword.setText("");
            GetAddress.setText("");
            GetPhoneNumber.setText("");

            // Display customer profile
            cus cusGUI = new cus(null,null);
            cusGUI.setCuID(customerRegister.getCustomerID());
            cusGUI.setCuPass(customerRegister.getPassword());
            cusGUI.displayCustomerProfile(customerRegister);
            // Switch to customer profile panel
            new Main().setVisible(false);
            this.dispose();
            cusGUI.setVisible(true);
            // Hide other panels if necessary
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void GetEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetEmailFocusGained
        if (GetEmail.getText().equals("Email")) {
            GetEmail.setText("");
        }
    }//GEN-LAST:event_GetEmailFocusGained

    private void GetEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetEmailFocusLost
        if (GetEmail.getText().isEmpty()) {
            GetEmail.setText("Email");
        }
    }//GEN-LAST:event_GetEmailFocusLost

    private void GetFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetFirstNameFocusGained
        if (GetFirstName.getText().equals("First Name")) {
            GetFirstName.setText("");
        }
    }//GEN-LAST:event_GetFirstNameFocusGained

    private void GetFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetFirstNameFocusLost
        if (GetFirstName.getText().isEmpty()) {
            GetFirstName.setText("First Name");
        }
    }//GEN-LAST:event_GetFirstNameFocusLost

    private void StaffIDLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffIDLoginFocusGained
        if (StaffIDLogin.getText().equals("Staff ID")) {
            StaffIDLogin.setText("");
        }    }//GEN-LAST:event_StaffIDLoginFocusGained

    private void StaffLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffLogInButtonActionPerformed
                String Id = StaffIDLogin.getText();
                String Password = new String(StaffPasswordLogin.getPassword());
                String Email= Staff_Email.getText();
                
                String role = new Login().log(Email, Id, Password);
                if (role != null) {
                    new Main().setVisible(false);
                    switch (role) {
                        case "Schedular":
                            new Main().setVisible(false);
                            this.dispose();
                            new Hall_Menu_GUI().setVisible(true);
                            break;
                        case "Adminstrator":
                            new Main().setVisible(false);
                            this.dispose();
                            new Admin(null).setVisible(true);
                            break;
                        case "Super Admin":
                            new Main().setVisible(false);
                            this.dispose();
                            new SuperAdmin(null).setVisible(true);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Unknown user role: " + role, "Error", JOptionPane.ERROR_MESSAGE);

                    }
                } 
    }//GEN-LAST:event_StaffLogInButtonActionPerformed

    private void StaffPasswordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffPasswordLoginFocusGained
        if (StaffPasswordLogin.getText().equals("Password")) {
            StaffPasswordLogin.setText("");
        }
    }//GEN-LAST:event_StaffPasswordLoginFocusGained

    private void StaffPasswordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffPasswordLoginFocusLost
        if (StaffPasswordLogin.getText().isEmpty()) {
            StaffPasswordLogin.setText("Password");
        }
    }//GEN-LAST:event_StaffPasswordLoginFocusLost

    private void StaffLogInPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffLogInPanelButtonActionPerformed
        StaffLoginPanel.setVisible(true);
        LoginPanel.setVisible(false);
    }//GEN-LAST:event_StaffLogInPanelButtonActionPerformed

    private void StaffIDLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffIDLoginFocusLost
        if (StaffIDLogin.getText().isEmpty()) {
            StaffIDLogin.setText("Staff ID");
        }
    }//GEN-LAST:event_StaffIDLoginFocusLost

    private void EmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailLoginActionPerformed

    private void GetPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetPhoneNumberActionPerformed

    private void Staff_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Staff_EmailFocusGained
        if(Staff_Email.getText().equals("Email")){
            Staff_Email.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_EmailFocusGained

    private void Staff_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Staff_EmailFocusLost
        if(Staff_Email.getText().equals("")){
            Staff_Email.setText("Email");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_EmailFocusLost

    private void SignUpButtonLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonLogIn1ActionPerformed
        StaffLoginPanel.setVisible(false);
        LoginPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonLogIn1ActionPerformed

    private void EXITButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITButtonActionPerformed

    private void EXITButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITButtonStaffActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITButtonStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateAccointLabel;
    protected javax.swing.JButton EXITButton;
    protected javax.swing.JButton EXITButtonStaff;
    protected javax.swing.JTextField EmailLogin;
    private javax.swing.JTextField GetAddress;
    private javax.swing.JTextField GetEmail;
    private javax.swing.JTextField GetFirstName;
    private javax.swing.JTextField GetLastName;
    private javax.swing.JPasswordField GetPassword;
    private javax.swing.JTextField GetPhoneNumber;
    protected javax.swing.JTextField IDLogin;
    protected javax.swing.JButton LogInButton;
    private javax.swing.JButton LoginButtonSignUp;
    public javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainMainPanel;
    protected javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JButton SignUpButton;
    protected javax.swing.JButton SignUpButtonLogIn;
    protected javax.swing.JButton SignUpButtonLogIn1;
    protected javax.swing.JTextField StaffIDLogin;
    protected javax.swing.JButton StaffLogInButton;
    private javax.swing.JButton StaffLogInPanelButton;
    private javax.swing.JPanel StaffLoginPanel;
    protected javax.swing.JPasswordField StaffPasswordLogin;
    protected javax.swing.JTextField Staff_Email;
    private javax.swing.JLabel WelcomeBackLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
